services:
  db:
    image: "postgres"
    restart: "always"
    environment:
      - "POSTGRES_DB=hackathon"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5433:5432"
    container_name: db

  web:
    build: .
    image: jusan-backend:stable
    container_name: api
    ports:
      - 8081:8081